# Generated by Django 2.2 on 2019-08-18 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=25, verbose_name='The Exam')),
                ('date', models.DateField(verbose_name='Date Held')),
                ('duration', models.DurationField(verbose_name='Time Duration')),
                ('active', models.BooleanField(default=False, verbose_name='Exam is active')),
            ],
        ),
        migrations.CreateModel(
            name='McqQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50, verbose_name='The MCQ Question')),
                ('answer_1', models.CharField(max_length=15, verbose_name='Answer 1')),
                ('answer_2', models.CharField(max_length=15, verbose_name='Answer 2')),
                ('answer_3', models.CharField(max_length=15, verbose_name='Answer 3')),
                ('answer_4', models.CharField(max_length=15, verbose_name='Answer 4')),
                ('correct', models.CharField(max_length=15, verbose_name='Correct answer')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampaper.Exam')),
            ],
            options={
                'verbose_name': 'MCQ Question',
                'verbose_name_plural': 'MCQ Questions',
            },
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcq_marks', models.PositiveIntegerField(null=True, verbose_name='Total MCQ paper marks')),
                ('essay_marks', models.PositiveIntegerField(null=True, verbose_name='Total Essay paper marks')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exampaper.Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EssayQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50, verbose_name='The Essay Question')),
                ('working_file', models.FileField(upload_to='', verbose_name='File to work and submit')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampaper.Exam')),
            ],
        ),
    ]
