# Generated by Django 2.2 on 2019-09-15 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=25, verbose_name='The Exam')),
                ('date', models.DateField(verbose_name='Date Held')),
                ('duration', models.DurationField(verbose_name='Time Duration')),
                ('active', models.BooleanField(default=False, verbose_name='Exam is active')),
            ],
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcq_marks', models.PositiveIntegerField(null=True, verbose_name='Total MCQ paper marks')),
                ('essay_marks', models.PositiveIntegerField(null=True, verbose_name='Total Essay paper marks')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exampaper.Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='McqQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50, verbose_name='The MCQ Question')),
                ('correct', models.CharField(max_length=25, verbose_name='Correct answer')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampaper.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='McqAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=25, verbose_name='Answer given')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Tick the correct answer')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exampaper.ExamPaper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampaper.McqQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='EssayQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50, verbose_name='The Essay Question')),
                ('working_file', models.FileField(upload_to='essay_questions/', verbose_name='File to work and submit')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampaper.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='EssayAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.FileField(upload_to='essay_answers/', verbose_name='Answer submitted')),
                ('marks', models.IntegerField(verbose_name='Marks')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exampaper.ExamPaper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampaper.EssayQuestion')),
            ],
        ),
    ]
