# Generated by Django 2.2 on 2019-09-15 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exampaper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essayanswer',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='mcqanswer',
            name='exam',
        ),
    ]
