# Generated by Django 2.2 on 2019-08-19 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exampaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqquestions',
            name='answer_1',
            field=models.CharField(max_length=25, verbose_name='Answer 1'),
        ),
        migrations.AlterField(
            model_name='mcqquestions',
            name='answer_2',
            field=models.CharField(max_length=25, verbose_name='Answer 2'),
        ),
        migrations.AlterField(
            model_name='mcqquestions',
            name='answer_3',
            field=models.CharField(max_length=25, verbose_name='Answer 3'),
        ),
        migrations.AlterField(
            model_name='mcqquestions',
            name='answer_4',
            field=models.CharField(max_length=25, verbose_name='Answer 4'),
        ),
        migrations.AlterField(
            model_name='mcqquestions',
            name='correct',
            field=models.CharField(max_length=25, verbose_name='Correct answer'),
        ),
        migrations.CreateModel(
            name='McqAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=25, verbose_name='Answer given')),
                ('is_correct', models.BooleanField(blank=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampaper.ExamPaper', verbose_name='Exam Paper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampaper.McqQuestions')),
            ],
        ),
        migrations.CreateModel(
            name='EssayAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.FileField(upload_to='', verbose_name='Answer submitted')),
                ('marks', models.IntegerField(verbose_name='Marks')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampaper.ExamPaper', verbose_name='Exam Paper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampaper.EssayQuestion')),
            ],
        ),
    ]
