# Generated by Django 2.2 on 2019-09-15 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exampaper', '0002_auto_20190915_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcqquestion',
            name='correct',
        ),
    ]
