# Generated by Django 2.2 on 2019-08-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampaper', '0002_auto_20190819_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqanswer',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
