# Generated by Django 2.2 on 2019-09-15 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exampaper', '0003_remove_mcqquestion_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='McqOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=25, verbose_name='Option for Question')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Tick the correct answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampaper.McqQuestion')),
            ],
        ),
        migrations.DeleteModel(
            name='McqAnswer',
        ),
    ]
