# Generated by Django 2.2 on 2019-08-19 05:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exampaper', '0003_auto_20190819_1058'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='essayanswer',
            unique_together={('paper', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='exampaper',
            unique_together={('student', 'exam')},
        ),
        migrations.AlterUniqueTogether(
            name='mcqanswer',
            unique_together={('paper', 'question')},
        ),
    ]
