# Generated by Django 2.2 on 2019-11-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampaper', '0005_auto_20190915_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqquestion',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='mcq_images/', verbose_name='Any image needed'),
        ),
    ]
