# Generated by Django 2.2 on 2019-11-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampaper', '0006_mcqquestion_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqoption',
            name='option',
            field=models.CharField(max_length=50, verbose_name='Option for Question'),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='question',
            field=models.CharField(max_length=150, verbose_name='The MCQ Question'),
        ),
    ]
