# Generated by Django 2.2 on 2019-11-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampaper', '0007_auto_20191115_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essayquestion',
            name='question',
            field=models.CharField(max_length=100, verbose_name='The Essay Question'),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='question',
            field=models.CharField(max_length=250, verbose_name='The MCQ Question'),
        ),
    ]
