# Generated by Django 2.2 on 2019-11-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampaper', '0008_auto_20191115_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqquestion',
            name='question',
            field=models.CharField(max_length=400, verbose_name='The MCQ Question'),
        ),
    ]
