# Generated by Django 2.2 on 2020-01-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampaper', '0011_auto_20191118_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayquestion',
            name='correct_file',
            field=models.FileField(blank=True, null=True, upload_to='essay_answers/', verbose_name='Correct Answer File'),
        ),
    ]
