# Generated by Django 2.2 on 2020-01-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampaper', '0012_essayquestion_correct_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essayanswer',
            name='marks',
            field=models.IntegerField(blank=True, null=True, verbose_name='Marks'),
        ),
    ]
