# Generated by Django 2.2 on 2020-01-15 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exampaper', '0014_essayanswer_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essayanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
