# Generated by Django 2.2 on 2020-01-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampaper', '0015_auto_20200115_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essayquestion',
            name='exam',
        ),
        migrations.AddField(
            model_name='exampaper',
            name='remaining_time',
            field=models.DurationField(null=True, verbose_name='Time Duration'),
        ),
        migrations.DeleteModel(
            name='EssayAnswer',
        ),
        migrations.DeleteModel(
            name='EssayQuestion',
        ),
    ]
