# Generated by Django 2.2 on 2020-01-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampaper', '0016_auto_20200119_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exampaper',
            name='essay_marks',
        ),
        migrations.AddField(
            model_name='exampaper',
            name='has_submitted',
            field=models.BooleanField(default=False, verbose_name='Paper is submitted'),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='remaining_time',
            field=models.DurationField(null=True, verbose_name='Remaining Time'),
        ),
    ]
