# Generated by Django 2.2 on 2020-01-19 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exampaper', '0017_auto_20200119_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='active',
        ),
    ]
